CREATE TABLE IF NOT EXISTS tb_users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(50) UNIQUE NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    password VARCHAR(255),
    auth VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_pricing_plans (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    plan_name VARCHAR(50) UNIQUE NOT NULL,
    price DOUBLE NOT NULL
);